/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repolab8p2_juanoliva_10741313;

import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author jr_02
 */
public class VentanaPrinicipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrinicipal
     */
    public VentanaPrinicipal() {
        initComponents();
        db = new BaseDatos("./Database/buses.dbj", "./Database/Estaciones.dbj");
        this.pack();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_AgregarBus = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jt_PlacaBus_Agregar = new javax.swing.JTextField();
        jt_MarcaBus_Agregar = new javax.swing.JTextField();
        jt_VelocidadBus_Agregar = new javax.swing.JTextField();
        jb_AgregarBus = new javax.swing.JButton();
        jc_ColorBus_Agregar = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Agregar Bus");

        jLabel2.setText("Placa");

        jLabel3.setText("Marca");

        jLabel4.setText("Color");

        jLabel5.setText("Velocidad");

        jb_AgregarBus.setText("Agregar Bus");
        jb_AgregarBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_AgregarBusActionPerformed(evt);
            }
        });

        jc_ColorBus_Agregar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amarillo", "Rojo", "Azul", "Negro" }));

        javax.swing.GroupLayout jd_AgregarBusLayout = new javax.swing.GroupLayout(jd_AgregarBus.getContentPane());
        jd_AgregarBus.getContentPane().setLayout(jd_AgregarBusLayout);
        jd_AgregarBusLayout.setHorizontalGroup(
            jd_AgregarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarBusLayout.createSequentialGroup()
                .addGroup(jd_AgregarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_AgregarBusLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jb_AgregarBus))
                    .addGroup(jd_AgregarBusLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jd_AgregarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_AgregarBusLayout.createSequentialGroup()
                                .addGroup(jd_AgregarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGroup(jd_AgregarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_AgregarBusLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jt_VelocidadBus_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jd_AgregarBusLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jd_AgregarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jt_PlacaBus_Agregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                            .addComponent(jt_MarcaBus_Agregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                            .addComponent(jc_ColorBus_Agregar, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jd_AgregarBusLayout.setVerticalGroup(
            jd_AgregarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AgregarBusLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_AgregarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_AgregarBusLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(jd_AgregarBusLayout.createSequentialGroup()
                        .addComponent(jt_PlacaBus_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jt_MarcaBus_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_AgregarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jc_ColorBus_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jd_AgregarBusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jt_VelocidadBus_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jb_AgregarBus)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Agregar Bus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jButton1)
                .addContainerGap(1234, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jButton1)
                .addContainerGap(628, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_AgregarBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_AgregarBusActionPerformed
        Bus b = new Bus();
        String nombre = jt_PlacaBus_Agregar.getText();
        String marca = jt_MarcaBus_Agregar.getText();
        double velocidad = 0;
        boolean v1 = !nombre.isEmpty();
        boolean v2 = !marca.isEmpty();
        boolean v3 = true;
        String temp = jt_VelocidadBus_Agregar.getText();
        for (int i = 0; i < temp.length(); i++) {
            if (!Character.isDigit(temp.charAt(i))) {
                v3 = false;
                break;
            }
        }
        if (v3) {
            velocidad = Double.valueOf(jt_VelocidadBus_Agregar.getText());
        }
        boolean validacion = v1&v2&v3;
        if (validacion) {
            b.setPlaca(nombre);
            b.setMarca(marca);
            b.setVelocidad(velocidad);
            b.setColor(colorBusAgregar);
            db.getBuses().add(b);
            JOptionPane.showMessageDialog(jd_AgregarBus, "El bus ha sido agregado exitosamente");
        }else{
            JOptionPane.showMessageDialog(jd_AgregarBus, "Revise los datos ingresados");
        }
    }//GEN-LAST:event_jb_AgregarBusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jd_AgregarBus.pack();
        jd_AgregarBus.setLocationRelativeTo(this);
        jd_AgregarBus.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrinicipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrinicipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrinicipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrinicipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrinicipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jb_AgregarBus;
    private javax.swing.JComboBox<String> jc_ColorBus_Agregar;
    private javax.swing.JDialog jd_AgregarBus;
    private javax.swing.JTextField jt_MarcaBus_Agregar;
    private javax.swing.JTextField jt_PlacaBus_Agregar;
    private javax.swing.JTextField jt_VelocidadBus_Agregar;
    // End of variables declaration//GEN-END:variables

    private  BaseDatos db;
    private Color colorBusAgregar;
    
    private void selecionarColor(){
        String s = jc_ColorBus_Agregar.getSelectedItem().toString();
        switch (s) {
            case "Amarillo":
                colorBusAgregar= Color.YELLOW;
                break;
            case "Rojo":
                colorBusAgregar = Color.RED;
                break;
            case "Azul":
                colorBusAgregar = Color.BLUE;
                break;
            case "Negro":
                colorBusAgregar = Color.BLACK;
                break;
            default:
                colorBusAgregar = Color.YELLOW;
                break;
        }
    }


}
